### ISSUE TITLE
Discussion: Roadmap for 1.0

### ISSUE THREAD

**Issue by Marlysson** [bykof/draper#1]
Guy, there is some roadmap of that features you intend implement on this project.

I would like help to implement them.

_I liked the proposals and objectives that will be achieved at end._

**Comment by bykof** [comment]
Cool man! Let's do this 👍 
What do you think, how to document the roadmap properly?

**Comment by Marlysson** [comment]
Like this:

https://github.com/tortoise/tortoise-orm/issues/19

This a good structure. Just pointing which features do you think about.

**Comment by bykof** [comment]
Okay lets start: 

- [x] Create models in the models application module on the fly without migrations (use mongoengine)
- [ ] Send events over kombu (created, updated and deleted events of the models)
- [ ] Use socket.io to deliver the events to websockets
- [ ] Automatically create REST Endpoints for the models 
- [ ] Create or use an authentication system 
- [ ] Write an admin frontend in React 
- [ ]

**Comment by Marlysson** [comment]
What do you think about use relational database to models applications and nosql to events ( application and tasks ) or would be over engineering ?

**Comment by bykof** [comment]
> What do you think about use relational database to models applications and nosql to events

If you are doing sql, you have to manage (alter) tables... I am doing web stuff more than 8 years now. It seems that everything you do in sql you also can do in nosql. I think that sql should be another feature in the future.
